#!/bin/bash
# Anon TV V2 - Push script
# این اسکریپت تمام تغییرات را به گیتهاب پوش میکند

set -e

echo "=== 📡 Anon TV V2 - Push to GitHub ==="
echo ""

# Check if we're in git repo
if [ ! -d ".git" ]; then
  echo "❌ Not a git repo! Run: git clone https://github.com/arammoostafaye/Iptv.git"
  exit 1
fi

# Check git status
echo "📊 Git status:"
git status --short
echo ""

# Add all new files
echo "➕ Adding files..."
git add .github/workflows/main.yml
git add .github/workflows/premium_scraper.yml
git add .gitignore
git add README.md
git add requirements.txt
git add core/
git add sources/
git add web/
git add update_iptv_v2.py
git add premium_sources.txt.example
git add UPGRADE_DONE.md
git add push_to_github.sh

# Don't add generated m3u files (they will be generated by Actions)
# git add *.m3u 2>/dev/null || true

echo ""
echo "📦 Staged files:"
git diff --cached --stat
echo ""

# Commit
read -p "📝 Commit message (default: Upgrade to V2 Professional): " MSG
MSG=${MSG:-"Upgrade to V2 Professional - 30+ sources, premium scraper, web player, multi-output"}

git commit -m "$MSG" || echo "Nothing to commit or already committed"

echo ""
echo "🚀 Pushing to origin main..."
git push origin main

echo ""
echo "✅ Done! Now go to:"
echo "   - https://github.com/arammoostafaye/Iptv/actions to see the workflow"
echo "   - Settings → Pages → Source: gh-pages to enable web player"
echo "   - https://arammoostafaye.github.io/Iptv/ for web player (after 2 min)"
